### ISSUE TITLE
[Request] Additional Mod Supports

### ISSUE THREAD

**Issue by Deadmano** [jwlei/ImmersiveHud#4]
Could I please request the option to hide elements from the following mods:

- [Groups](https://thunderstore.io/c/valheim/p/Smoothbrain/Groups/)
- [WackyEpicMMOSystem](https://thunderstore.io/c/valheim/p/WackyMole/WackyEpicMMOSystem/)
- [AzuClock](https://thunderstore.io/c/valheim/p/Azumatt/AzuClock/)

**Comment by jwlei** [comment]
Probably wont add compatibility for these in the forseeable future
